apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: parktrack-prod

resources:
  - ../../base

images:
  - name: ghcr.io/parktrack-project/api-server-app
    newTag: latest
  - name: ghcr.io/parktrack-project/api-server-migrate
    newTag: latest
  - name: ghcr.io/parktrack-project/car-detector
    newTag: latest
  - name: ghcr.io/parktrack-project/web-map
    newTag: latest
  - name: ghcr.io/parktrack-project/admin-panel
    newTag: latest

replicas:
  - name: api-server
    count: 1
  - name: web-map
    count: 1
  - name: admin-panel
    count: 1
