apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - gateway.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - postgres/secret.yaml
  - api-server/deployment.yaml
  - api-server/service.yaml
  - api-server/configmap.yaml
  - api-server/secret.yaml
  - api-server/http-route.yaml
  - car-detector/deployment.yaml
  - web-map/deployment.yaml
  - web-map/service.yaml
  - web-map/http-route.yaml
  - admin-panel/deployment.yaml
  - admin-panel/service.yaml
  - admin-panel/http-route.yaml
